# Generated by Django 5.2.8 on 2025-11-24 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyindex', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('replylevel', models.IntegerField(editable=False)),
                ('replycontent', models.TextField()),
                ('post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
