# Generated by Django 5.2.8 on 2025-11-24 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcontent',
            fields=[
                ('postcontentindex', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('postcontenttag', models.CharField(max_length=255)),
                ('postindex', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='Object3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectfile', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('postcontentindex', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='postcontent.postcontent')),
            ],
        ),
        migrations.CreateModel(
            name='Image2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('postcontentindex', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='postcontent.postcontent')),
            ],
        ),
        migrations.CreateModel(
            name='Blogcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogcontext', models.TextField()),
                ('postcontentindex', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='postcontent.postcontent')),
            ],
        ),
    ]
