# Generated by Django 5.2.8 on 2025-11-24 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postindex', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('posttitle', models.CharField(max_length=255)),
                ('postdescription', models.TextField()),
                ('posttag', models.CharField(max_length=255)),
                ('isInPublic', models.BooleanField(default=True)),
            ],
        ),
    ]
