# Generated by Django 5.2.8 on 2025-11-24 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_index_1st', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=127, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_password_2nd', models.CharField(max_length=255, null=True)),
                ('user_index_2nd', models.UUIDField(default=uuid.uuid4)),
                ('user_index_3rd', models.UUIDField(default=uuid.uuid4)),
                ('user_status', models.SmallIntegerField(choices=[(-1, 'Suspended User'), (1, 'Normal User'), (8, 'Admin'), (16, 'Developer'), (32, 'Project Manager'), (64, 'Founder')], default=1)),
                ('user_level', models.SmallIntegerField(choices=[(1, 'Unranked User'), (2, 'Bronze User'), (3, 'Silver User'), (4, 'Gold User'), (5, 'Platinum User')], default=1)),
                ('user_join_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('user_info_index_1st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('user_phone_number', models.CharField(max_length=15, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('user_alt_name', models.CharField(max_length=255, null=True)),
                ('user_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMediaSubmission',
            fields=[
                ('user_info_index_1st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('user_header_image', models.ImageField(upload_to='header_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserUISetup',
            fields=[
                ('user_info_index_1st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('setup_locale', models.CharField(default='en-GB', max_length=16)),
                ('enable_vertical_mode', models.BooleanField(default=False)),
                ('setup_theme', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCloseFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('befriend_date_time', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL)),
                ('friend_request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('friend', 'friend_request_by')},
            },
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date_time', models.DateTimeField(auto_now_add=True)),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('following', 'followed_by')},
            },
        ),
    ]
