# Generated by Django 5.2.8 on 2025-11-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('localeIdx', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='localeIdx')),
                ('localecode', models.CharField(max_length=15)),
                ('nativelangname', models.CharField(max_length=63)),
                ('vieworientation', models.IntegerField(choices=[(0, 'Lr Tb'), (1, 'Rl Tb'), (2, 'Tb Lr And Rl Tb'), (3, 'Tb Rl And Lr Tb')])),
            ],
        ),
    ]
